services:
  prediction-api:
    build: .
    container_name: prediction-api
    ports:
      - "8083:8080"
    environment:
      - MONGODB_URI=mongodb://${MONGO_PREDICTION_USER}:${MONGO_PREDICTION_PASSWORD}@mongo:27017/tennis?authSource=tennis
      - SERVER_PORT=8080
    networks:
      - api-tennis-simple-adapter_tennis-network
    restart: unless-stopped

networks:
  api-tennis-simple-adapter_tennis-network:
    external: true
